export const AUDIO_LIST = [
  {
    attachment:
      "https://github.com/outZoNe/DiscordPidorBot/raw/master/assets/a-chleny-dymyatsya-pidory-konchayut-daaaaaaa.mp3",
  },
  {
    attachment:
      "https://github.com/outZoNe/DiscordPidorBot/raw/master/assets/a-gde-sosal-ty-tam-upala-pizda.mp3",
  },
  {
    attachment:
      "https://github.com/outZoNe/DiscordPidorBot/raw/master/assets/andrei.mp3",
  },
  {
    attachment:
      "https://github.com/outZoNe/DiscordPidorBot/raw/master/assets/pesnya-zanovo-pidorom-stat-zanovo-zanovo.mp3",
  },
  {
    attachment:
      "https://github.com/outZoNe/DiscordPidorBot/raw/master/assets/vechno-gomogei.mp3",
  },
  {
    attachment:
      "https://github.com/outZoNe/DiscordPidorBot/raw/master/assets/ver-ace-cover-feat-nerroweyed-kizaru-zerkalo-gay-remix.mp3",
  },
  {
    attachment:
      "https://github.com/outZoNe/DiscordPidorBot/raw/master/assets/versus-oxxxymiron-feat-alla-pugacheva.mp3",
  },
];
